# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Books"
  url = "#books"
  weight = 20
#when time to put the book links live, cut the teaching tab and adjust the ones before that to be later (consider calling "publications" "papers" and shortening names of other things; also set up a link to invite to come talk/consulting fees etc.)

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Papers"
  url = "#publications"
  weight = 40

[[main]]
  name = "Talks"
  url = "#conference"
  weight = 50

[[main]]
  name = "Teaching"
  url = "#experience"
  weight = 60

[[main]]
  name = "Awards"
  url = "#accomplishments"
  weight = 70

[[main]]
  name = "Poetry"
  url = "#poet"
  weight = 80

[[main]]
  name = "Photography"
  url = "#slider"
  weight = 90

 [[main]]
    name = "Resources"
    url = "#clinical"
    weight = 100


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 110
